import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/CustomCursor"; // Import CustomCursor

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Me amas dayyy?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const showCustomCursor = true; // Set to false to easily disable

  return (
    <html lang="en">
      {showCustomCursor && (
        <style jsx global>{`
          body, a, button {
            cursor: none !important; /* Ensure default cursor is hidden */
          }
        `}</style>
      )}
      <body className={inter.className}>
        {showCustomCursor && <CustomCursor />}
        {children}
      </body>
    </html>
  );
}
